### ISSUE TITLE
Path projection onto video

### ISSUE THREAD

**Issue by mattwhiteEB** [Bothell-Professional-Development/Auto-Vision-Lane-Detection#2]
# Input:
* vector representation of processed image.
   * 2d vector of image marking true where a lane is found, zero where lane isn't fount

# Output:
* some sort of super-imposition of the original video (needs to be researched) for the center of the lane, but not the patch of the vehicle

**Comment by mattwhiteEB** [comment]
@TallPatrick I'd say this issue can be closed (as the path is being projected, it just can now use some improvement) - no use in keeping it around, right?

**Comment by TallPatrick** [comment]
Yup!  It is implemented now.  Pretty close to the final version too.
